
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox;

	private global::Gtk.Table table1;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.Button button6;

	private global::Gtk.Button button7;

	private global::Gtk.Button button8;

	private global::Gtk.Button button9;

	private global::Gtk.VBox vbox1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textview;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button buttonPVP;

	private global::Gtk.Button buttonXBot;

	private global::Gtk.Button buttonOBot;

	private global::Gtk.Button buttonTryAgain;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox = new global::Gtk.HBox();
		this.hbox.Name = "hbox";
		this.hbox.Homogeneous = true;
		this.hbox.Spacing = 6;
		// Container child hbox.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.table1.Add(this.button1);
		// Container child table1.Gtk.Table+TableChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.table1.Add(this.button2);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.button2]));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.table1.Add(this.button3);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.button3]));
		w3.LeftAttach = ((uint)(2));
		w3.RightAttach = ((uint)(3));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.table1.Add(this.button4);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.button4]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.table1.Add(this.button5);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.button5]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		// Container child table1.Gtk.Table+TableChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.table1.Add(this.button6);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.button6]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.LeftAttach = ((uint)(2));
		w6.RightAttach = ((uint)(3));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.table1.Add(this.button7);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.button7]));
		w7.TopAttach = ((uint)(2));
		w7.BottomAttach = ((uint)(3));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button8 = new global::Gtk.Button();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.table1.Add(this.button8);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.button8]));
		w8.TopAttach = ((uint)(2));
		w8.BottomAttach = ((uint)(3));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.table1.Add(this.button9);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.button9]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.LeftAttach = ((uint)(2));
		w9.RightAttach = ((uint)(3));
		this.hbox.Add(this.table1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox[this.table1]));
		w10.Position = 0;
		w10.Expand = false;
		// Container child hbox.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview = new global::Gtk.TextView();
		this.textview.Sensitive = false;
		this.textview.CanFocus = true;
		this.textview.Name = "textview";
		this.GtkScrolledWindow.Add(this.textview);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w12.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.buttonPVP = new global::Gtk.Button();
		this.buttonPVP.CanFocus = true;
		this.buttonPVP.Name = "buttonPVP";
		this.buttonPVP.UseUnderline = true;
		this.buttonPVP.Label = global::Mono.Unix.Catalog.GetString("PVP");
		this.hbox5.Add(this.buttonPVP);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.buttonPVP]));
		w13.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.buttonXBot = new global::Gtk.Button();
		this.buttonXBot.CanFocus = true;
		this.buttonXBot.Name = "buttonXBot";
		this.buttonXBot.UseUnderline = true;
		this.buttonXBot.Label = global::Mono.Unix.Catalog.GetString("X BOT");
		this.hbox5.Add(this.buttonXBot);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.buttonXBot]));
		w14.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.buttonOBot = new global::Gtk.Button();
		this.buttonOBot.CanFocus = true;
		this.buttonOBot.Name = "buttonOBot";
		this.buttonOBot.UseUnderline = true;
		this.buttonOBot.Label = global::Mono.Unix.Catalog.GetString("O BOT");
		this.hbox5.Add(this.buttonOBot);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.buttonOBot]));
		w15.Position = 2;
		this.vbox1.Add(this.hbox5);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.buttonTryAgain = new global::Gtk.Button();
		this.buttonTryAgain.CanFocus = true;
		this.buttonTryAgain.Name = "buttonTryAgain";
		this.buttonTryAgain.UseUnderline = true;
		this.buttonTryAgain.Label = global::Mono.Unix.Catalog.GetString("Try Again");
		this.vbox1.Add(this.buttonTryAgain);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.buttonTryAgain]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		this.hbox.Add(this.vbox1);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox[this.vbox1]));
		w18.Position = 1;
		this.Add(this.hbox);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 848;
		this.DefaultHeight = 514;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button9.Clicked += new global::System.EventHandler(this.OnButtonClicked);
		this.button8.Clicked += new global::System.EventHandler(this.OnButtonClicked);
		this.button7.Clicked += new global::System.EventHandler(this.OnButtonClicked);
		this.button6.Clicked += new global::System.EventHandler(this.OnButtonClicked);
		this.button5.Clicked += new global::System.EventHandler(this.OnButtonClicked);
		this.button4.Clicked += new global::System.EventHandler(this.OnButtonClicked);
		this.button3.Clicked += new global::System.EventHandler(this.OnButtonClicked);
		this.button2.Clicked += new global::System.EventHandler(this.OnButtonClicked);
		this.button1.Clicked += new global::System.EventHandler(this.OnButtonClicked);
		this.buttonPVP.Clicked += new global::System.EventHandler(this.OnButtonModeClicked);
		this.buttonXBot.Clicked += new global::System.EventHandler(this.OnButtonModeClicked);
		this.buttonOBot.Clicked += new global::System.EventHandler(this.OnButtonModeClicked);
		this.buttonTryAgain.Clicked += new global::System.EventHandler(this.OnButtonTryAgainClicked);
	}
}
